package com.nextech.erp.constants;

public class ERPConstants {
	public static String COUNT="count";
	public static String SESSIONTIMEOUT="sessionTimeout";
	public static String FIRSTNAME="firstName";
	public static String STATUS_READY_STORE_IN="readyStoreIn";
    public static String STATUS_RAW_MATERIAL_INVENTORY_ADD="statusRMInventoryAdd";
    public static String STATUS_NEW_PRODUCT_ORDER="newProductOrder";
    public static String STATUS_NEW_RM_ORDER="newRMOrder";
    public static String EMAIL_ALREADY_EXIT="emailExit";
    public static String VENDOR_ADDED_SUCCESSFULLY="vendorAddedSuccessfully";
    public static String VENDOR_UPDATE_SUCCESSFULLY="vendorUpdateSuccessfully";
    public static String CLIENT_ADDED_SUCCESSFULLY="clientAddedSuccessfully";
    public static String CLIENT_UPDATE_SUCCESSFULLY="clientUpdateSuccessfully";
    public static String DISPATCHED_SUCCESSFULLY="dispatchedSuccessfully";
    public static String COMPANY_NAME_EXIT="companyName";
    public static String STATUS_RAW_MATERIAL_ORDER_COMPLETE="rmOrderComplete";
    public static String CLIENT_ADDED="clientAdded";
    public static String USER_ID="userId";
    public static String CONTACT_NUMBER_EXIT="contactNumberXit";
    public static String PRODUCT_NAME="productName";
    public static String PART_NUMBER="partNumber";
    public static String CLIENT_UPDATE="updateClient";
    public static String CLIENT_DELETE="deleteClinet";
    public static String RM_QUALITY_CHECK="rawMaterilQualityCheck";
    public static String INFO_QUALITY_CHECK="infoProvideForQualityCheck";
    public static String QC_RM_ORDER_NOT_FOUND="rmOrderNotFound";
    public static String PRODUCT_RM_ASSO_EXIT="productRMExit";
    public static String VENDOR_RM_ASSO_EXIT="vendorRMExit";
    public static String PRODUCT_INVENTORY_ASSO_EXIT="productInventoryExit";
    public static String RAW_MATERIAL_INVENTORY="rawMaterialInventoryExit";
    public static String PRODUCT_DATE_EXIT="productDateExit";
    public static String RAW_MATERAIL_ADD="rawMaterilAdd";
    public static String RAW_MATERAIL_UPDATE="rawMaterilUpdate";
    public static String RAW_MATERAIL_DELETE="rawMaterilDelete";
    public static  String STATUS_RAW_MATERIAL_ORDER_INCOMPLETE = "statusRMOrderIncomplete";
    public static  String PROD_PLAN_IN_PROGRESS = "ProdPlanInProgress";
    public static  String PROD_PLAN_NEW = "ProdPlanNew";
    public static String PRODUCTION_PLAN_READY_TO_START ="productionPlanReadyToStart";
    public static  String PROD_PLAN_COMPLETE = "ProdPlanComplete";
    public static  String STATUS_QUALITY_CHECK_PENDING = "statusQualityCheckPending";
    public static String STATUS_QUALITY_CHECK_INPROGRESS="statusQualityCheckInprogess";
    public static String STATUS_SECURITY_CHECK_INVOICE_IN ="statusSecurityCheck";
    public static String STATUS_QUALITY_CHECK_INVOICE_IN ="statuQualityCheckInvoices";
    public static String STATUS_QUALITY_CHECK_COMPLETE ="statuQualityCheckComplete";
    public static String RM_ORDER_INVOICE_EXIT="rawMaterailOrderInvoiceExit";
    public static String CREATED_BY="createdBy";
    public static String STATUS_INVOICE_IN="invoiceIn";
    public static String STATUS_QUALITY_CHECK="qualityCheck";
    public static String STATUS_RAW_MATERIAL_INPROCESS="rmInProcess";
    public static String STATUS_RAW_MATERIAL_INCOMPLETE="rmInComplete";
    public static String STATUS_PRODUCT__INVENTORY_ADD="productInventoryAdd";
    public static String SESSION_EXPIRED="Session Expired! Please login again.";
    public static String STATUS_PRODUCT_ORDER_INCOMPLETE="productOrderIncomplete";
    public static String STATUS_PRODUCT_ORDER_COMPLETE="productOrderComplete";
   public static String ORDER_DISPATCHED="orderDispatched";
   public static String ORDER_SECURITY_OUT="orderSecuirtyCheckout";
   public static String ORDER_DISPATCHED_COMPLETE="orderDispatchedComplete";
   public static String SECURITY_CHECK_COMPLETE="securityCheckOutComplete";
   public static String ADDED_STORE_OUT="storeOut";
   public static String TO_CHECK_QUANTITY_IN_PRODUCTINVENTORY="checkquantityInProductInventory";
   public static String TO_CHECK_QUANTITY_IN_RMINVENTORY="checkquantityInRMInventory";

   public static String STORE_OUT_PARTIAL="STORE_OUT_PARTIAL";
   public static String STORE_OUT_COMPLETE="STORE_OUT_COMPLETE";
   public static String USER_ADD_NOTIFICATION="useraddNotification";
   public static String USER_UPDATE_NOTIFICATION="userupdateNotifiaction";


}
