package com.nextech.dreamConstruction.constants;

public class DreamConstructionConstants {
	public static String COUNT="count";
	public static String SESSIONTIMEOUT="sessionTimeout";
	public static String FIRSTNAME="firstName";
    public static String STATUS_NEW_PRODUCT_ORDER="newProductOrder";
    public static String STATUS_NEW_RM_ORDER="newRMOrder";
    public static String EMAIL_SHOULD_BE_UNIQUE="emailExit";
    public static String VENDOR_ADDED_SUCCESSFULLY="vendorAddedSuccessfully";
    public static String VENDOR_UPDATE_SUCCESSFULLY="vendorUpdateSuccessfully";
    public static String CLIENT_ADDED_SUCCESSFULLY="clientAddedSuccessfully";
    public static String CLIENT_UPDATE_SUCCESSFULLY="clientUpdateSuccessfully";
    public static String DISPATCHED_SUCCESSFULLY="dispatchedSuccessfully";
    public static String COMPANY_NAME_SHOULD_BE_UNIQUE="companyName";
    public static String CLIENT_ADDED="clientAdded";
    public static String USER_ID_SHOULD_BE_UNIQUE="userId";
    public static String CONTACT_NUMBER_SHOULD_BE_UNIQUE="contactNumberXit";
    public static String PRODUCT_NAME_SHOULD_BE_UNIQUE="productName";
    public static String PART_NUMBER_SHOULD_BE_UNIQUE="partNumber";
    public static String CLIENT_UPDATE="updateClient";
    public static String CLIENT_DELETE="deleteClinet";
    public static String PRODUCT_RM_ASSO_EXIT="productRMExit";
    public static String VENDOR_RM_ASSO_EXIT="vendorRMExit";
    public static String PRODUCT_INVENTORY_ASSO_EXIT="productInventoryExit";
    public static String PRODUCT_DATE_EXIT="productDateExit";
    public static String CREATED_BY="createdBy";
    public static String STATUS_PRODUCT__INVENTORY_ADD="productInventoryAdd";
   public static String TO_CHECK_QUANTITY_IN_PRODUCTINVENTORY="checkquantityInProductInventory";
   public static String STATUS_PRODUCT_ORDER_COMPLETE="productOrderComplete";
   public static String STATUS_PRODUCT_ORDER_INCOMPLETE="productOrderIncomplete";
   public static String SESSION_EXPIRED="Session Expired! Please login again.";
   public static String USER_FORGOT_NOTIFICATION="userForgotNotifiaction";
   public static String USER_UPDATE_NOTIFICATION="userupdateNotifiaction";
   public static String USER_ADD_NOTIFICATION="useraddNotification";
   public static String CLIENT_ADD_NOTIFICATION="clientaddNotification";
   public static String CLIENT_UPDATE_NOTIFICATION="clientUpdateNotification";
   public static String PURCHASE_ORDER_INCOMPLETE="purchaseOrderIncomplete";
   public static String PURCHASE_NEW_PRODUCT="purchaseNewProduct";
   public static String PURCHASE_ORDER_COMPLETE="purchaseOrderComplete";
   public static String VENDOR_ADD_NOTIFICATION="vendorAddNotification";
   public static String VENDOR_UPDATE_NOTIFICATION="vendorUpdateNotification";
}
